# Generated by Django 2.2.6 on 2022-02-22 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.SmallIntegerField(verbose_name='社团id')),
                ('recruit_num', models.SmallIntegerField(verbose_name='招新人数')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='截止时间')),
                ('interview_rounds', models.SmallIntegerField(verbose_name='面试轮数')),
            ],
        ),
    ]
