# Generated by Django 2.2.6 on 2022-02-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.SmallIntegerField(verbose_name='姓名')),
                ('club_id', models.SmallIntegerField(verbose_name='意向社团')),
                ('first_department', models.CharField(max_length=16, verbose_name='第一意向部门')),
                ('second_department', models.CharField(max_length=16, verbose_name='第二意向部门')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('current', models.SmallIntegerField(verbose_name='当前状态')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('institute', models.CharField(max_length=50, verbose_name='学院')),
                ('major', models.CharField(max_length=30, verbose_name='专业')),
                ('phone_num', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('qq', models.CharField(max_length=11, unique=True, verbose_name='qq')),
                ('self_introduction', models.CharField(max_length=200, verbose_name='自我介绍')),
            ],
            options={
                'verbose_name': '个人简历表',
                'verbose_name_plural': '个人简历表',
                'unique_together': {('resume_name', 'phone_num', 'qq')},
            },
        ),
    ]
