# Generated by Django 2.2.6 on 2022-02-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=30, unique=True, verbose_name='社团名称')),
                ('introduction', models.TextField(verbose_name='社团简介')),
                ('department', models.CharField(max_length=256, verbose_name='拥有部门')),
            ],
            options={
                'verbose_name': '社团信息表',
                'verbose_name_plural': '社团信息表',
            },
        ),
    ]
