# Generated by Django 2.2.6 on 2022-02-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='club_picture',
            field=models.ImageField(blank=True, null=True, upload_to='club_picture/', verbose_name='社团活动照'),
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='logo'),
        ),
        migrations.AlterUniqueTogether(
            name='clubinfo',
            unique_together={('club_name', 'logo')},
        ),
    ]
