# Generated by Django 2.2.6 on 2022-02-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubinfo', '0002_auto_20220222_2213'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clubinfo',
            unique_together=set(),
        ),
    ]
